exec-once = pgrep -f random-wall.sh || ~/.config/hypr/random-wall.sh
exec-once = pgrep -f battery-notif.sh || ~/.config/hypr/battery-notif.sh
exec-once = wl-paste --watch cliphist store
exec-once = mako
exec-once = qs
exec-once = hyprsunset
